name: CI
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: printenv
      - run: echo "Run unit tests v2"
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo build complete
